### ISSUE TITLE
Payload binding error 

### ISSUE THREAD

**Issue by Gregnald** [noob-hackers/m-wiz#10]
Please solve this 
![IMG_20210319_200559.jpg](https://user-images.githubusercontent.com/79373546/111797111-d90c7b80-88ee-11eb-9323-06a74c550588.jpg)

**Comment by infraredracoon1** [comment]
This is a common Ruby error which indicates that the method or attribute for an object you are trying to call on an object has not been defined.
NoMethodError: undefined method SOME_METHOD for nil:NilClass
For example, the String class in Ruby has the method size (which is synonymous with length, so I can write...
greeting = "hello"
greeting.size
#=> 5
But loveliness does not exist for a string, so when I type it, I will get...
NoMethodError: undefined method loveliness for nil:NilClass 
Of course, because this is Ruby, we can actually define objects easily by monkeypatching
